import preDesignFrames from './preDesignFrames'
import singleCustomFrame from './SingleCustomFrame'
import multipleCustomFrame from './MultipleCustomFrame'
import marketingTools from './marketingTools'
import aboutUs from './aboutUs'
import faq from './faq'
import privacyPolicy from './privacyPolicy'
import termsOfService from './termsOfService'
import returnRefundPolicy from './returnRefundPolicy'
import shippingPolicy from './shippingPolicy'
import review from './review'
import socialLinks from './socialLinks'
import seo from './seo'
import affiliateSeo from './affiliateSeo'
import framesSeo from './framesSeo'
import heroImages from './heroImages'
import exploreByStyle from './exploreByStyle'

export const schemaTypes = [preDesignFrames, singleCustomFrame, multipleCustomFrame, marketingTools, aboutUs, faq, privacyPolicy, termsOfService, returnRefundPolicy, shippingPolicy, review, socialLinks, seo, affiliateSeo, framesSeo, heroImages, exploreByStyle]
